### ISSUE TITLE
about the new version of opendrive support

### ISSUE THREAD

**Issue by ArtistZhou** [snow-orld/opendrive#2]
hi, i add the data from www.atlatec.de to the project but because of the version add new geometry it can not show.
![image](https://user-images.githubusercontent.com/16474670/66627866-8cb80900-ec2f-11e9-862d-fff54a1a8b32.png)
do you have plan to update the parase code to version 1.5 ?thank you

**Comment by snow-orld** [comment]
Hi, since I have recently switched my focus onto other subjects related to self-driving cars, I do not have the plan to update it to a new version.
Actually OpenDRIVE Format 1.4 also defines geometry types poly3 and paramPoly3 which does not occur in the sample data provided by the OpenDRIVE offical website. You can add the parsing part for these geometry types if possible. Drawing methods also need implementing for poly3 and paramPoly3.
